---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myblog
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myblog
  targetCPUUtilizationPercentage: 50