# Default values for myblog-helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

myblog:
  image:
    repository: 634087373040.dkr.ecr.eu-north-1.amazonaws.com/myblog
    tag: "0.0.1"
  initDbJob:
    force: false

nginx:
  image:
    repository: 634087373040.dkr.ecr.eu-north-1.amazonaws.com/nginx
    tag: "0.0.1"

postgres:
  image:
    repository: postgres
    tag: 12

